

version: '3'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes: 
      - mariadb:/var/lib/mysql:nocopy
    # - /Users/jo/data/mariadb:/var/lib/mysql
    restart: unless-stopped # "on-failure", container will be restarted 
    expose:
      - "3306"



  nginx:           # with TLSv.1.2
    container_name: nginx # name of the container
    volumes:
      - wordpress:/var/www/wordpress:nocopy
    networks:
      - inception
    depends_on:
      - wordpress
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure # "on-failure", container will be restarted 

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
    - wordpress:/var/www/wordpress:nocopy
    networks:
      - inception
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:    # wordpress will be started after mariadb
      - mariadb
    restart: unless-stopped # "on-failure", container will be restarted 
    expose: 
      - "9000"


## VOLUME CHECK

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'pathtodata/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'pathtodata/mariadb'



#network part
networks:
    inception:
      driver: bridge